### ISSUE TITLE
Speed up workflow checks

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/scpcaTools#27]
Our CI checks for the workflow are a bit slow, mostly because every time we run them, we are reinstalling all the dependencies for scpcaTools. If we were to use the image from https://github.com/AlexsLemonade/alsf-scpca/tree/main/images/scpca-r, we should be able to speed these checks quite substantially.

**Comment by jaclyn-taroni** [comment]
I don’t know _how slow_ this is so it is hard for me to comment on cost-benefit, but I wanted to ask — do you think think there’s some merit to testing these install steps? Particularly if the Docker image is built somewhat infrequently

**Comment by jashapiro** [comment]
Slow is 20 minutes sometimes. The install steps are for dependencies that are not our problem, in my mind. (The docker image should not include scpcaData; that would still get installed on each run.) there is some chance that we would catch dependency version conflicts/changes with the current setup, but I think that is pretty small.

We could also do both! Use docker for PR checks and the full install for pushes to main.

**Comment by allyhawkins** [comment]
CI is now failing because of package install it looks like, while no errors are seen locally, so as Josh pointed out it might be worth bumping up priority on this. Including some of the links to errors thrown during install of dependencies during a CI run that failed for reference: 
https://github.com/AlexsLemonade/scpcaTools/pull/29/checks?check_run_id=3255336874#step:4:263
https://github.com/AlexsLemonade/scpcaTools/pull/29/checks?check_run_id=3255336874#step:4:7770

**Comment by jashapiro** [comment]
Closing this, as the new version of the R CMD check action seems to do more caching, which improves processing times.
